<?php

namespace Database\Seeders;

use App\Models\RiceVariety;
use Illuminate\Database\Seeder;

class RiceVarietySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $varieties = [
            [
                'name' => 'IR 64',
                'description' => 'Varietas adaptif dengan hasil stabil di berbagai kondisi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.5,
                'maturity_days' => 115,
            ],
            [
                'name' => 'Ciherang',
                'description' => 'Varietas unggul nasional dengan potensi hasil tinggi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 8.0,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Mekongga',
                'description' => 'Varietas premium dengan kualitas beras superior dan hasil tinggi',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 8.5,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Inpari 30',
                'description' => 'Varietas unggul dengan hasil baik di dataran rendah',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.8,
                'maturity_days' => 113,
            ],
            [
                'name' => 'Inpari 32',
                'description' => 'Varietas tahan genangan dan banjir',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 7.0,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Inpari 42',
                'description' => 'Varietas tahan kekeringan dan lahan marjinal',
                'soil_type' => 'ultisol',
                'rainfall_category' => 'rawan_kekeringan',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'tadah_hujan',
                'salinity_category' => 'normal',
                'threats' => ['rawan_kekeringan'],
                'yield_potential' => 6.5,
                'maturity_days' => 115,
            ],
            [
                'name' => 'Inpari IR Nutri Zinc',
                'description' => 'Varietas dengan kandungan zinc tinggi untuk nutrisi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.2,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Situ Bagendit',
                'description' => 'Varietas spesifik lokasi untuk lahan sawah dataran tinggi',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 6.1,
                'maturity_days' => 123,
            ],
            [
                'name' => 'Cigeulis',
                'description' => 'Varietas dengan produktivitas tinggi dan beras berkualitas',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.6,
                'maturity_days' => 123,
            ],
            [
                'name' => 'Dodokan',
                'description' => 'Varietas lokal dengan hasil stabil di berbagai kondisi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.0,
                'maturity_days' => 108,
            ],
            [
                'name' => 'Fatmawati',
                'description' => 'Varietas unggul dengan hasil baik di dataran rendah',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.5,
                'maturity_days' => 113,
            ],
            [
                'name' => 'Situ Patenggang',
                'description' => 'Varietas spesifik lokasi untuk dataran tinggi Bandung',
                'soil_type' => 'ultisol',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'dingin',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 5.5,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Situ Lembang',
                'description' => 'Varietas untuk dataran tinggi dengan hasil stabil',
                'soil_type' => 'ultisol',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'dingin',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 5.8,
                'maturity_days' => 130,
            ],
            [
                'name' => 'Limboto',
                'description' => 'Varietas lokal dengan adaptasi iklim tropis',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.3,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Towuti',
                'description' => 'Varietas lokal unggul dari Sulawesi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 7.4,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Kalimutu',
                'description' => 'Varietas lokal dengan hasil baik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.2,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Batutegi',
                'description' => 'Varietas lokal dengan ketahanan terhadap hama',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.1,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Inpara 1',
                'description' => 'Varietas tahan genangan untuk lahan rawa',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.5,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Inpara 2',
                'description' => 'Varietas tahan genangan dengan hasil baik',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.6,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Inpara 3',
                'description' => 'Varietas tahan genangan untuk lahan rawa',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.7,
                'maturity_days' => 123,
            ],
            [
                'name' => 'Inpara 4',
                'description' => 'Varietas tahan genangan dengan hasil stabil',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.8,
                'maturity_days' => 123,
            ],
            [
                'name' => 'Inpara 5',
                'description' => 'Varietas tahan genangan untuk lahan rawa',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.5,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Inpara 6',
                'description' => 'Varietas tahan genangan dengan hasil baik',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.6,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Inpara 7',
                'description' => 'Varietas tahan genangan untuk lahan rawa',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.7,
                'maturity_days' => 123,
            ],
            [
                'name' => 'Inpara 8',
                'description' => 'Varietas tahan genangan dengan hasil stabil',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.8,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Inpara 9',
                'description' => 'Varietas tahan genangan untuk lahan rawa',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.9,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Banyuasin',
                'description' => 'Varietas lokal dengan hasil baik',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.9,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Margasari',
                'description' => 'Varietas untuk dataran tinggi dengan hasil stabil',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 6.2,
                'maturity_days' => 130,
            ],
            [
                'name' => 'Pandanwangi',
                'description' => 'Varietas beras wangi premium dengan aroma khas',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'tadah_hujan',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.5,
                'maturity_days' => 158,
            ],
            [
                'name' => 'Rojolele',
                'description' => 'Varietas beras merah dengan kualitas premium',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.0,
                'maturity_days' => 150,
            ],
            [
                'name' => 'Mentik Wangi',
                'description' => 'Varietas beras wangi premium dari Jawa Tengah',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.2,
                'maturity_days' => 140,
            ],
            [
                'name' => 'Adan Krayan',
                'description' => 'Varietas beras merah lokal dari Kalimantan',
                'soil_type' => 'gambut',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 5.8,
                'maturity_days' => 165,
            ],
            [
                'name' => 'Pare Bau',
                'description' => 'Varietas beras merah aromatik dari Kalimantan',
                'soil_type' => 'gambut',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 5.7,
                'maturity_days' => 165,
            ],
            [
                'name' => 'Pulu Mandoti',
                'description' => 'Varietas beras merah lokal dari Sulawesi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 5.9,
                'maturity_days' => 163,
            ],
            [
                'name' => 'Siam Unus',
                'description' => 'Varietas beras merah dari Thailand yang adaptif',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.1,
                'maturity_days' => 145,
            ],
            [
                'name' => 'Padi Merah Banyumas',
                'description' => 'Varietas beras merah lokal dari Banyumas',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.0,
                'maturity_days' => 140,
            ],
            [
                'name' => 'Padi Merah Bali',
                'description' => 'Varietas beras merah lokal dari Bali',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.1,
                'maturity_days' => 145,
            ],
            [
                'name' => 'Padi Merah Toraja',
                'description' => 'Varietas beras merah premium dari Toraja',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 5.9,
                'maturity_days' => 160,
            ],
            [
                'name' => 'Padi Hitam Cempo',
                'description' => 'Varietas beras hitam premium dari Cempo',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 5.5,
                'maturity_days' => 150,
            ],
            [
                'name' => 'Padi Hitam Toraja',
                'description' => 'Varietas beras hitam premium dari Toraja',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 5.4,
                'maturity_days' => 165,
            ],
            [
                'name' => 'Padi Hitam Tasikmalaya',
                'description' => 'Varietas beras hitam dari Tasikmalaya',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 5.6,
                'maturity_days' => 150,
            ],
            [
                'name' => 'Nagina 22',
                'description' => 'Varietas premium dengan aroma khas',
                'soil_type' => 'ultisol',
                'rainfall_category' => 'rawan_kekeringan',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'tadah_hujan',
                'salinity_category' => 'normal',
                'threats' => ['rawan_kekeringan'],
                'yield_potential' => 6.8,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Sahbhagi Dhan',
                'description' => 'Varietas unggul dengan hasil stabil',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_sederhana',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.2,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Vandana',
                'description' => 'Varietas tahan kekeringan dan lahan marjinal',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'rawan_kekeringan',
                'temperature_optimal' => 'dingin',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_sederhana',
                'salinity_category' => 'normal',
                'threats' => ['rawan_kekeringan'],
                'yield_potential' => 6.5,
                'maturity_days' => 130,
            ],
            [
                'name' => 'DRR Dhan 42',
                'description' => 'Varietas tahan kekeringan dengan hasil baik',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.3,
                'maturity_days' => 128,
            ],
            [
                'name' => 'Inpago 8',
                'description' => 'Varietas unggul dengan produktivitas tinggi',
                'soil_type' => 'ultisol',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'tadah_hujan',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.0,
                'maturity_days' => 115,
            ],
        ];

        foreach ($varieties as $variety) {
            RiceVariety::create($variety);
        }
    }
}
