<?php

namespace Database\Seeders;

use App\Models\RiceVariety;
use Illuminate\Database\Seeder;

class RiceVarietySeeder extends Seeder
{
    /**
     * Run the database seeds untuk rice varieties
     * Total: 46 varietas padi dari berbagai daerah di Indonesia
     */
    public function run(): void
    {
        $varieties = [
            // 5 Varietas SAW untuk fitur rekomendasi
            [
                'name' => 'Nagina 22',
                'description' => 'Varietas unggul dari India, adaptif dengan hasil stabil',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.2,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Sahbhagi Dhan',
                'description' => 'Varietas dari India dengan tingkat adaptasi tinggi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.8,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Vandana',
                'description' => 'Varietas lokal dengan adaptasi iklim tropis baik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'toleran_salin',
                'threats' => ['rawan_banjir', 'rawan_hama'],
                'yield_potential' => 6.5,
                'maturity_days' => 128,
            ],
            [
                'name' => 'DRR Dhan 42',
                'description' => 'Varietas dari India dengan hasil konsisten',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.0,
                'maturity_days' => 122,
            ],
            [
                'name' => 'Inpago 8',
                'description' => 'Varietas unggul nasional dengan potensi hasil tinggi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.5,
                'maturity_days' => 115,
            ],

            // 41 Varietas Tambahan untuk fitur jadwal tanam
            [
                'name' => 'IR 64',
                'description' => 'Varietas adaptif dengan hasil stabil di berbagai kondisi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.5,
                'maturity_days' => 115,
            ],
            [
                'name' => 'Ciherang',
                'description' => 'Varietas unggul nasional dengan potensi hasil tinggi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.8,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Mentik Wangi',
                'description' => 'Padi wangi lokal dengan kualitas beras premium',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 5.8,
                'maturity_days' => 130,
            ],
            [
                'name' => 'Limboto',
                'description' => 'Varietas lokal dengan adaptasi iklim tropis',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.3,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Towuti',
                'description' => 'Varietas lokal unggul dari Sulawesi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 7.4,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Kalimutu',
                'description' => 'Varietas lokal dengan hasil baik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.1,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Bluggur',
                'description' => 'Varietas lokal dari Jawa Timur',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_menengah',
                'water_availability' => 'irigasi_sederhana',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.5,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Bengawan',
                'description' => 'Varietas lokal untuk dataran tinggi dengan hasil stabil',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 5.5,
                'maturity_days' => 135,
            ],
            [
                'name' => 'Kahayan',
                'description' => 'Varietas lokal dari Kalimantan',
                'soil_type' => 'gambut',
                'rainfall_category' => 'tinggi',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.0,
                'maturity_days' => 128,
            ],
            [
                'name' => 'Kapuas',
                'description' => 'Varietas lokal dari Kalimantan Barat',
                'soil_type' => 'gambut',
                'rainfall_category' => 'tinggi',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'toleran_salin',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 5.8,
                'maturity_days' => 130,
            ],
            [
                'name' => 'Martapura',
                'description' => 'Varietas untuk rawa dengan hasil baik',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'toleran_salin',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.2,
                'maturity_days' => 132,
            ],
            [
                'name' => 'Banyuasin',
                'description' => 'Varietas lokal dengan hasil baik',
                'soil_type' => 'rawa',
                'rainfall_category' => 'rawan_banjir',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'rawa',
                'salinity_category' => 'normal',
                'threats' => ['rawan_banjir'],
                'yield_potential' => 6.9,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Margasari',
                'description' => 'Varietas untuk dataran tinggi dengan hasil stabil',
                'soil_type' => 'liat',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 5.5,
                'maturity_days' => 135,
            ],
            [
                'name' => 'Situ Patenggang',
                'description' => 'Varietas untuk dataran tinggi Jawa Barat',
                'soil_type' => 'ultisol',
                'rainfall_category' => 'tinggi',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 5.2,
                'maturity_days' => 140,
            ],
            [
                'name' => 'Sintanur',
                'description' => 'Varietas unggul nasional dengan daya adaptasi baik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.2,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Atomita',
                'description' => 'Varietas tahan kekeringan',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'rawan_kekeringan',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'tadah_hujan',
                'salinity_category' => 'normal',
                'threats' => ['rawan_kekeringan'],
                'yield_potential' => 5.5,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Dodokan',
                'description' => 'Varietas lokal tahan kekeringan',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'rawan_kekeringan',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'tadah_hujan',
                'salinity_category' => 'normal',
                'threats' => ['rawan_kekeringan'],
                'yield_potential' => 5.3,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Barito',
                'description' => 'Varietas dengan daya adaptasi tinggi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.0,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Cisadane',
                'description' => 'Varietas unggul dari Jawa Barat',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.3,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Cibodas',
                'description' => 'Varietas untuk dataran tinggi dengan adaptasi baik',
                'soil_type' => 'ultisol',
                'rainfall_category' => 'tinggi',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 5.0,
                'maturity_days' => 145,
            ],
            [
                'name' => 'Badak Putih',
                'description' => 'Padi putih dengan kualitas beras baik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.1,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Padi Merah Genjah',
                'description' => 'Varietas beras merah dengan umur genjah',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 5.8,
                'maturity_days' => 100,
            ],
            [
                'name' => 'Padi Merah Thailand',
                'description' => 'Varietas beras merah dari Thailand yang adaptif',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.1,
                'maturity_days' => 145,
            ],
            [
                'name' => 'Padi Merah Banyumas',
                'description' => 'Varietas beras merah lokal dari Banyumas',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 5.9,
                'maturity_days' => 135,
            ],
            [
                'name' => 'Padi Hitam Banyumas',
                'description' => 'Varietas padi hitam lokal dari Banyumas',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 5.5,
                'maturity_days' => 140,
            ],
            [
                'name' => 'IR 36',
                'description' => 'Varietas standar dengan hasil stabil',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.8,
                'maturity_days' => 110,
            ],
            [
                'name' => 'IR 42',
                'description' => 'Varietas dengan daya adaptasi tinggi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.9,
                'maturity_days' => 115,
            ],
            [
                'name' => 'Way Apo Buru',
                'description' => 'Varietas lokal dari Lampung',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.0,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Way Rarem',
                'description' => 'Varietas lokal dari Lampung dengan hasil baik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.95,
                'maturity_days' => 122,
            ],
            [
                'name' => 'Binuang',
                'description' => 'Varietas lokal dari Bangka',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.8,
                'maturity_days' => 125,
            ],
            [
                'name' => 'Rasi',
                'description' => 'Varietas dengan hasil stabil di berbagai kondisi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.7,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Sélénding',
                'description' => 'Varietas padi putih lokal dari Yogyakarta',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.5,
                'maturity_days' => 130,
            ],
            [
                'name' => 'Mangga',
                'description' => 'Varietas padi lokal dengan nama unik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.3,
                'maturity_days' => 128,
            ],
            [
                'name' => 'Gunung Putih',
                'description' => 'Varietas lokal dengan adaptasi ketinggian baik',
                'soil_type' => 'ultisol',
                'rainfall_category' => 'tinggi',
                'temperature_optimal' => 'sedang',
                'elevation_category' => 'dataran_tinggi',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_angin_kencang'],
                'yield_potential' => 5.1,
                'maturity_days' => 142,
            ],
            [
                'name' => 'Padi Ketan Putih',
                'description' => 'Varietas padi ketan dengan hasil baik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 6.2,
                'maturity_days' => 132,
            ],
            [
                'name' => 'Padi Ketan Hitam',
                'description' => 'Varietas padi ketan hitam dengan kualitas premium',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 5.9,
                'maturity_days' => 138,
            ],
            [
                'name' => 'Inpago 6',
                'description' => 'Varietas unggul nasional dengan hasil baik',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.2,
                'maturity_days' => 120,
            ],
            [
                'name' => 'Inpago 7',
                'description' => 'Varietas unggul nasional generasi terbaru',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.4,
                'maturity_days' => 118,
            ],
            [
                'name' => 'Inpago 9',
                'description' => 'Varietas unggul nasional dengan daya adaptasi tinggi',
                'soil_type' => 'aluvial',
                'rainfall_category' => 'sedang',
                'temperature_optimal' => 'panas',
                'elevation_category' => 'dataran_rendah',
                'water_availability' => 'irigasi_teknis',
                'salinity_category' => 'normal',
                'threats' => ['rawan_hama'],
                'yield_potential' => 7.3,
                'maturity_days' => 120,
            ],
        ];

        foreach ($varieties as $variety) {
            RiceVariety::create($variety);
        }
    }
}
